global:
  scrape_interval: 3s
  evaluation_interval: 3s
  external_labels:
    cluster: 'petfamily-dev'
    environment: 'docker'

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  # API Gateway
  - job_name: 'api-gateway'
    metrics_path: '/metrics'
    static_configs:
      - targets: ['api-gateway:8080']
    relabel_configs:
      - source_labels: [__address__]
        target_label: instance
        replacement: 'api-gateway'

  # Auth Service
  - job_name: 'auth-service'
    metrics_path: '/metrics'
    static_configs:
      - targets: ['auth-service:8080']
    relabel_configs:
      - source_labels: [__address__]
        target_label: instance
        replacement: 'auth-service'

  # VolunteerManagement Service
  - job_name: 'volunteer-management-service'
    metrics_path: '/metrics'
    static_configs:
      - targets: ['volunteer-management-service:8080']
    relabel_configs:
      - source_labels: [__address__]
        target_label: instance
        replacement: 'volunteer-management-service'

  # Notification Service
  - job_name: 'notification-service'
    metrics_path: '/metrics'
    static_configs:
      - targets: ['notification-service:8080']
    relabel_configs:
      - source_labels: [__address__]
        target_label: instance
        replacement: 'notification-service'

  # FileStorage Service
  - job_name: 'filestorage-service'
    metrics_path: '/metrics'
    static_configs:
      - targets: ['filestorage-service:8080']
    relabel_configs:
      - source_labels: [__address__]
        target_label: instance
        replacement: 'filestorage-service'

  # Account Service
  - job_name: 'account-service'
    metrics_path: '/metrics'
    static_configs:
      - targets: ['account-service:8080']
    relabel_configs:
      - source_labels: [__address__]
        target_label: instance
        replacement: 'account-service'

  # Conversation Service
  - job_name: 'conversation-service'
    metrics_path: '/metrics'
    static_configs:
      - targets: ['conversation-service:8080']
    relabel_configs:
      - source_labels: [__address__]
        target_label: instance
        replacement: 'conversation-service'

  - job_name: 'rabbitmq'
    static_configs:
      - targets: ['rabbitmq:15692']
    relabel_configs:
      - source_labels: [__address__]
        target_label: instance
        replacement: 'rabbitmq'

  - job_name: 'postgres-auth'
    static_configs:
      - targets: ['postgres-exporter-auth:9187']
    relabel_configs:
      - source_labels: [__address__]
        target_label: instance
        replacement: 'postgres-auth'

  - job_name: 'postgres-volunteer-management'
    static_configs:
      - targets: ['postgres-exporter-volunteer-management:9187']
    relabel_configs:
      - source_labels: [__address__]
        target_label: instance
        replacement: 'postgres-volunteer-management'

  - job_name: 'postgres-notification'
    static_configs:
      - targets: ['postgres-exporter-notification:9187']
    relabel_configs:
      - source_labels: [__address__]
        target_label: instance
        replacement: 'postgres-notification'

  - job_name: 'postgres-account'
    static_configs:
      - targets: ['postgres-exporter-account:9187']
    relabel_configs:
      - source_labels: [__address__]
        target_label: instance
        replacement: 'postgres-account'

  - job_name: 'postgres-conversation'
    static_configs:
      - targets: ['postgres-exporter-conversation:9187']
    relabel_configs:
      - source_labels: [__address__]
        target_label: instance
        replacement: 'postgres-conversation'

  - job_name: 'redis'
    static_configs:
      - targets: ['redis-exporter:9121']
    relabel_configs:
      - source_labels: [__address__]
        target_label: instance
        replacement: 'redis'
