name: Publish Multiple NuGet Packages

on:
  release:
    types: [created]

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
    
    strategy:
      matrix:
        include:
          - project: VolunteerManagement.Contracts
            package-id: PetFamily.VolunteerManagement.Contracts
          - project: PetFamily.SharedKernel.Domain
            package-id: PetFamily.SharedKernel.Domain
          - project: PetFamily.SharedKernel.Infrastructure
            package-id: PetFamily.SharedKernel.Infrastructure
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'
          source-url: https://nuget.pkg.github.com/haxnted/index.json
        env:
          NUGET_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}
      
      - name: Pack ${{ matrix.project }}
        run: dotnet pack Solution/${{ matrix.project }}/${{ matrix.project }}.csproj --configuration Release -p:PackageVersion=${{ github.ref_name }} --output ./packages
      
      - name: Push ${{ matrix.package-id }}
        run: dotnet nuget push ./packages/${{ matrix.package-id }}.*.nupkg --skip-duplicate
